### ISSUE TITLE
写了一个类似 demo

### ISSUE THREAD

**Issue by fantasticit** [page-pipepline/pipeline-editor#11]
https://blog.wipi.tech/ramiko/editor

https://github.com/fantasticit/ramiko

最近一直在研究公司的营销页面搭建工具，尝试写了一个核心编辑器的实现，今天又看到大佬的实现，哈哈。

**Comment by CntChen** [comment]
看起来不错哈. 

有兴趣可以参考下 pipeline 的相关文章.
* [页面可视化搭建工具前生今世](https://github.com/CntChen/cntchen.github.io/issues/15)
* [页面可视化搭建工具技术要点](https://github.com/CntChen/cntchen.github.io/issues/17)

**Comment by fantasticit** [comment]
对，就是看这个博客看到这里的。 哈哈
