### ISSUE TITLE
学习学习

### ISSUE THREAD

**Issue by liutao** [page-pipepline/pipeline-editor#2]
最近准备做一个类似的平台，看到了你写的文章，刚才简单看了一眼。这种拖住模块，然后编辑模块数据的方式，应该是可视化搭建页面里面最简单的一种了吧。
有几个问题：
1、没有服务端的代码吗？
2、最终也没是ssr渲染的吧，没有考虑部分模块数据是ajax的么？
大体上感觉。。现在完全是一个玩具，只是最最简单的能跑起来。

**Comment by CntChen** [comment]
感谢提 issue!

回复你的几个问题:
1. 有[后台代码](https://github.com/page-pipepline/pipeline-node-server)和[模板工程](https://github.com/page-pipepline/pipeline-template)。
2. 服务端渲染是在后台代码中实现的，主要解决的问题是快速生成页面；页面中的模块是否需要 ajax 异步请求开发人员可以自行实现，模块就是一个前端框架（vue）的组件，页面生成工具并不限制其业务功能。 我后续添加一个待接口请求的示例上去。

这个框架还是挺不错的，已经在我公司内部实现落地和支持前端业务；希望这个项目可以给你做的事情提供一些参考。

**Comment by CntChen** [comment]
已经添加了动态接口示例，欢迎体验。 @liutao 
![image](https://user-images.githubusercontent.com/4598445/41702437-bbefb9d8-7562-11e8-83ea-c5817e475e39.png)

**Comment by liutao** [comment]
666。。。感谢感谢

**Comment by Jialufeng** [comment]
东西是好东西，就是部署好麻烦。。。
