### ISSUE TITLE
自定义组件报错

### ISSUE THREAD

**Issue by zhijianfree** [page-pipepline/pipeline-editor#4]
你好，我创建自定义组件之后。在Editer页面展示的时候报如下错误，麻烦看下是什么原因产生的：

![image](https://user-images.githubusercontent.com/21210211/57779351-809b4e80-7758-11e9-9ec6-3f853d318945.png)

**Comment by CntChen** [comment]
从报错看不出具体原因，可能是组件的配置字段不匹配，可以先在组件库跑以下两个命令，看是否有报错：
```
$ npm run server # pipeline 后台构建
$ npm run render # 后台构建后本地验证渲染结果
```
