### ISSUE TITLE
服务端node-server设计思路的疑问：

### ISSUE THREAD

**Issue by pea-jj** [page-pipepline/pipeline-editor#6]
你好，看了下几个项目，有如下几点疑问：
1 关于pageId，我看着每选择一次模板就会生成一个pageid，每生成一次pageid，就会进行拷贝模板的操作，这样node层体积会不会越来越大？  什么时候会删除无效的 pageid 文件夹，（因为如果不发布，当前操作就应该算作无效的）。
2 我认为模板应该是固定的，比如一个vue组件库，以这个模板去发布，应该 空间 只有一个地方存储就好，但是好像 每个pageId都要做存储，目的是什么？
3 对页面配置的更改，（排序、props） 最后对应于 node端对 文件json的更改，这样会不会 慢， 还是应该把数据放在数据库里会不会更好

**Comment by CntChen** [comment]
好问题. 你已经完全了解pipleline的工作机制了.
从模板生成的页面代码, 完成编辑后, 需要"发布"到静态资源服务器, 同时生成zip落库. 现在项目是少了发布步骤. 我抽空补充上.

1. 拷贝模板可以认为是生成一份pageid的页面代码. 这个页面代码编辑完成后, 需要发布到外网机器上, 同时生成压缩包落库. 这个时候pageid文件夹其实就可以删除了, 也可以定时任务对一段时间内没改动的目录做清空.
2. 这是2个理念. 你这种做法是页面一份, 但是有很多份配置, 页面打开时获取配置做展示. 这个也是可行的. 但是需要有配置后台接口支持.
但是多个页面的话可以做页面单独管理, 比如有页面A和页面B, 组件库升级了, 可以重新编辑B和发布B, 对A没有影响. 同一份模板代码, 升级可能有阻碍. 
3. 在页面发布时候, 是会将页面信息落库, 页面生成zip另外存储. 下次需要修改页面, 直接解压zip到pageid目录, 就可以再次编辑了.
node端生成json文件, 其实很快, 并且这种系统是内部为主, 并发量有限.

**Comment by pea-jj** [comment]
感谢老板回答。
1 已理解。如果应用到项目上，有个 新建 page 的概念我觉得会比较好，不浪费存储。
2 多个页面 确实能做到升级不用回归老页面的情况。 但不知道这样是否值得，业务更多的情况是 模板固定，组件库增加，每次使用最新组件库模板 也是没问题的。也不会多一次网络请求，也可以是在node层做的吧。 只不过不能 做二次开发。 有点纠结，不知道贵公司  这种方案落地了吗，有木有什么问题。
3  由于假设每个页面都不同，所以需要发布存储zip。cdn上会多了许多差异不大的文件，好在是内部用，数量有限。
这种方式对于发布来说，每个页面都对应一份静态资源，需要建立一套自动化部署流程，这一步也要有基础建设。  想想 还是页面加载后 前端请求数据配置 来的直接 。 但云凤蝶 好像也是后端构建好的。
实时编辑预览用iframe的时候  还有一种 postmessage 方案，不知道 与pipline  直接后台渲染对比优劣对比是啥。     云凤蝶 在实时编辑的时候，iframe 的src 和预览 还是不一样的， 看不出是怎么做的。

**Comment by CntChen** [comment]
其实服务器硬盘空间很便宜的, cdn厂商多是对流量进行收费.

问题2:
我上家公司就是落地多页面的方案。 一直用同一份代码, 后续组件增多会导致编辑器膨胀, 可能页面改动也会对旧功能带来风险。
问题3: 
存储上硬盘很便宜的, 没问题。
自动部署流程是一个跨机器的资源包同步，正常来说不难搞，公司有运维同学，那就更好了。
云凤蝶肯定是多页面的， 因为它的页面要单独交付给不同的用户。

前端或后端渲染:
做前端渲染是可行的, 但是渲染就要求页面有当前前端框架，比如vue，react， 难以做到和前端框架无关, [可以看下这篇 pipeline的技术介绍](https://github.com/CntChen/cntchen.github.io/issues/17)。
云凤蝶的前端框架是自己的, 可能会更加灵活一点。 后台做感觉更稳， 前端渲染搞出个数据流和布局问题可能有坑。

发布配置还是发布页面:
单独发配置来修改页面是有专门系统的, 叫做[前端配置管理系统](https://github.com/CntChen/for-slides/blob/master/c.pdf)，但是定位不一样。 前端配置系统是用来做通用的前端配置，提升业务功能的灵活性。页面可视化搭建是页面生产的高效性。
