### ISSUE TITLE
当自定义的组件很多时，如果控制打包出来 js 文件的大小？

### ISSUE THREAD

**Issue by zhongxia245** [page-pipepline/pipeline-editor#7]
请教个问题，
比如当有30个组件的时候，如果按照动态渲染组件的方式，因为不知道到底会用到哪几个组件，因此webpack会把30个组件都打包到 js 里面，js 很大。这个问题如何控制， 或者如何解决这个问题？

![image](https://user-images.githubusercontent.com/7597581/64594355-6f024480-d3e2-11e9-89ac-7db182e61b9f.png)

**Comment by CntChen** [comment]
好问题, 可以在前端框架那里做处理, 实现**按需加载**. 大多数前端框架应该支持按需加载的.
比如 vue 模板工程中的实现, 可以看[这里](https://github.com/page-pipepline/pipeline-template/blob/master/src/App.vue#L20)
```js
components: {
    'pipeline-header-demo': () => import('comp/pipeline-header-demo'),
    'pipeline-info-demo': () => import('comp/pipeline-info-demo'),
    'pipeline-gap-demo': () => import('comp/pipeline-gap-demo'),
    'pipeline-weather-demo': () => import('comp/pipeline-weather-demo'),
  },
```

比如只用1个组件时只加载一个js:
（前面那4个是html的 preload, 可以去掉的)
![image](https://user-images.githubusercontent.com/4598445/64598982-36b33400-d3eb-11e9-832b-12915876c650.png)

用2个组件时按需加载2个组件的js:
![image](https://user-images.githubusercontent.com/4598445/64599175-82fe7400-d3eb-11e9-9d8d-e91f6a385cc7.png)

**Comment by zhongxia245** [comment]
感谢大佬，受教了。
